changelog:
  categories:
    - title: Added
      labels:
        - "new feature"
    - title: Changed
      labels:
        - enhancement
    - title: Fixed
      labels:
        - bug
    - title: Security
      labels:
        - dependencies
