name: Deploy
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: x64
    - name: Build package
      run: poetry build
    - name: Publish to PyPI
      run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
