name: Extra

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.os }} • py${{ matrix.python-version }} • extra:${{ matrix.extra }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
        extra: [noextra, data, xml, vtl]
        include:
          - extra: noextra
            marker: noextra
            extras_to_install: ""
          - extra: data
            marker: data
            extras_to_install: "data"
          - extra: xml
            marker: xml
            extras_to_install: "xml data"
          - extra: vtl
            marker: vtl
            extras_to_install: "vtl"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pipx install poetry

      - name: Install deps (${{ matrix.extras_to_install }})
        shell: bash
        run: |
          set -euo pipefail
          if [ -n "${{ matrix.extras_to_install }}" ]; then
            for e in ${{ matrix.extras_to_install }}; do
              poetry install --no-interaction --extras "$e"
            done
          else
            poetry install --no-interaction
          fi
      - name: Validate forbidden packages per extra
        shell: bash
        run: |
          set -euo pipefail

          installed="$(poetry show --tree | grep -E '^[A-Za-z0-9._-]+' | awk '{print tolower($1)}' | sort -u)"
          
          echo "Installed packages (first 50 lines):"
          echo "$installed" | head -n 50

          fail=0
          assert_not_installed() {
            pkg="$1"
            if echo "$installed" | grep -qx "$pkg"; then
              echo "❌ Forbidden package was installed: $pkg"
              fail=1
            fi
          }

          case "${{ matrix.extra }}" in
            noextra)
              assert_not_installed "xmltodict"
              assert_not_installed "numpy"
              assert_not_installed "vtlengine"
              ;;
            data)
              assert_not_installed "xmltodict"
              assert_not_installed "vtlengine"
              ;;
            xml)
              assert_not_installed "vtlengine"
              ;;
            vtl)
              assert_not_installed "xmltodict"
              assert_not_installed "numpy"
              ;;
          esac

          if [ "$fail" -ne 0 ]; then
            echo "❌ Some forbidden packages were installed for extra '${{ matrix.extra }}'."
            exit 1
          fi

      - name: Run tests (${{ matrix.marker }})
        run: poetry run pytest -m "${{ matrix.marker }}" --cov=pysdmx --cov-branch



